# Write your MySQL query statement below
SELECT DISTINCT VISITED_ON,
AMOUNT,AVERAGE_AMOUNT FROM
(
SELECT  VISITED_ON,
sum(amount) over (order by visited_on RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW) AS AMOUNT,
ROUND(SUM(AMOUNT) OVER (ORDER BY VISITED_ON RANGE BETWEEN INTERVAL 6 DAY PRECEDING AND CURRENT ROW)/7,2) AS AVERAGE_AMOUNT
FROM CUSTOMER
) A
WHERE VISITED_ON >= DATE_ADD((SELECT MIN(VISITED_ON) FROM CUSTOMER),INTERVAL 6 DAY);